name: CI/CD Pipeline for OpenTelemetry Demo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} # Add your AWS Access Key in GitHub Secrets
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # Add your AWS Secret Access Key in GitHub Secrets
          aws-region: us-east-1 # Replace with your AWS region if different

      - name: Authenticate with Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up kubectl
        run: |
          aws eks --region us-east-1 update-kubeconfig --name otel-demo-cluster # Replace otel-demo-cluster with your EKS cluster name

      - name: Apply Kubernetes Manifests
        run: |
          kubectl apply -f opentelemtry-demo.yaml -n otel-demo --validate=false # Path to your Kubernetes manifest file

      - name: Verify Deployment
        run: |
          kubectl get pods

rollback:
    runs-on: ubuntu-latest
    if: failure()
    needs: deploy
    steps:
      - name: Set up AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region us-east-1
  
      - name: Set up kubectl
        run: |
          aws eks --region us-east-1 update-kubeconfig --name otel-demo-cluster
  
      - name: Rollback opentelemetry-demo-accountingservice
        run: |
          kubectl rollout undo deployment/opentelemetry-demo-accountingservice

      - name: Rollback opentelemetry-demo-adservice
        run: |
          kubectl rollout undo deployment/opentelemetry-demo-adservice

      - name: Rollback opentelemetry-demo-cartservice
        run: |
          kubectl rollout undo deployment/opentelemetry-demo-cartservice

      - name: Rollback opentelemetry-demo-checkoutservice
        run: |
          kubectl rollout undo deployment/opentelemetry-demo-checkoutservice

      - name: Rollback opentelemetry-demo-currencyservice
        run: |
          kubectl rollout undo deployment/opentelemetry-demo-currencyservice

      - name: Rollback opentelemetry-demo-emailservice
        run: |
          kubectl rollout undo deployment/opentelemetry-demo-emailservice

      - name: Rollback opentelemetry-demo-flagd
        run: |
          kubectl rollout undo deployment/opentelemetry-demo-flagd

      - name: Rollback opentelemetry-demo-frauddetectionservice
        run: |
          kubectl rollout undo deployment/opentelemetry-demo-frauddetectionservice

      - name: Rollback opentelemetry-demo-frontend
        run: |
          kubectl rollout undo deployment/opentelemetry-demo-frontend

      - name: Rollback opentelemetry-demo-frontendproxy
        run: |
          kubectl rollout undo deployment/opentelemetry-demo-frontendproxy

      - name: Rollback opentelemetry-demo-imageprovider
        run: |
          kubectl rollout undo deployment/opentelemetry-demo-imageprovider

      - name: Rollback opentelemetry-demo-jaeger
        run: |
          kubectl rollout undo deployment/opentelemetry-demo-jaeger

      - name: Rollback opentelemetry-demo-kafka
        run: |
          kubectl rollout undo deployment/opentelemetry-demo-kafka

      - name: Rollback opentelemetry-demo-loadgenerator
        run: |
          kubectl rollout undo deployment/opentelemetry-demo-loadgenerator

      - name: Rollback opentelemetry-demo-paymentservice
        run: |
          kubectl rollout undo deployment/opentelemetry-demo-paymentservice

      - name: Rollback opentelemetry-demo-productcatalogservice
        run: |
          kubectl rollout undo deployment/opentelemetry-demo-productcatalogservice

      - name: Rollback opentelemetry-demo-quoteservice
        run: |
          kubectl rollout undo deployment/opentelemetry-demo-quoteservice

      - name: Rollback opentelemetry-demo-recommendationservice
        run: |
          kubectl rollout undo deployment/opentelemetry-demo-recommendationservice

      - name: Rollback opentelemetry-demo-shippingservice
        run: |
          kubectl rollout undo deployment/opentelemetry-demo-shippingservice

      - name: Rollback opentelemetry-demo-valkey
        run: |
          kubectl rollout undo deployment/opentelemetry-demo-valkey
