name: CI/CD Pipeline for AWS EKS

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and Push Docker Images
      env:
        ECR_URI: 283565981308.dkr.ecr.us-east-1.amazonaws.com/otel-demo
      run: |
        IMAGES=(
            "frontendproxy"
            "loadgenerator"
            "frontend"
            "checkoutservice"
            "currencyservice"
            "shippingservice"
            "frauddetectionservice"
            "recommendationservice"
            "adservice"
            "productcatalogservice"
            "quoteservice"
            "flagdui"
            "cartservice"
            "accountingservice"
            "emailservice"
            "paymentservice"
            "imageprovider"
            "kafka"
        )
        for IMAGE in "${IMAGES[@]}"; do
            docker build -t $ECR_URI:$IMAGE -f ./Dockerfile .
            docker push $ECR_URI:$IMAGE
        done

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Update Kubernetes Manifests
      run: |
        sed -i 's|ghcr.io/open-telemetry/demo|283565981308.dkr.ecr.us-east-1.amazonaws.com/otel-demo|g' kubernetes/opentelemetry-demo.yaml

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f kubernetes/opentelemetry-demo.yaml -n otel-demo

    - name: Verify Deployment Rollout
      run: |
        kubectl rollout status deployment/frontendproxy -n otel-demo

      run: |
        sed -i 's|ghcr.io/open-telemetry/demo:.*-frontendproxy|283565981308.dkr.ecr.us-east-1.amazonaws.com/otel-demo:frontendproxy|g' kubernetes/opentelemetry-demo.yaml
        sed -i 's|ghcr.io/open-telemetry/demo:.*-loadgenerator|283565981308.dkr.ecr.us-east-1.amazonaws.com/otel-demo:loadgenerator|g' kubernetes/opentelemetry-demo.yaml
        sed -i 's|ghcr.io/open-telemetry/demo:.*-frontend|283565981308.dkr.ecr.us-east-1.amazonaws.com/otel-demo:frontend|g' kubernetes/opentelemetry-demo.yaml
        sed -i 's|ghcr.io/open-telemetry/demo:.*-checkoutservice|283565981308.dkr.ecr.us-east-1.amazonaws.com/otel-demo:checkoutservice|g' kubernetes/opentelemetry-demo.yaml
        sed -i 's|ghcr.io/open-telemetry/demo:.*-currencyservice|283565981308.dkr.ecr.us-east-1.amazonaws.com/otel-demo:currencyservice|g' kubernetes/opentelemetry-demo.yaml
        sed -i 's|ghcr.io/open-telemetry/demo:.*-shippingservice|283565981308.dkr.ecr.us-east-1.amazonaws.com/otel-demo:shippingservice|g' kubernetes/opentelemetry-demo.yaml
        sed -i 's|ghcr.io/open-telemetry/demo:.*-frauddetectionservice|283565981308.dkr.ecr.us-east-1.amazonaws.com/otel-demo:frauddetectionservice|g' kubernetes/opentelemetry-demo.yaml
        sed -i 's|ghcr.io/open-telemetry/demo:.*-recommendationservice|283565981308.dkr.ecr.us-east-1.amazonaws.com/otel-demo:recommendationservice|g' kubernetes/opentelemetry-demo.yaml
        sed -i 's|ghcr.io/open-telemetry/demo:.*-adservice|283565981308.dkr.ecr.us-east-1.amazonaws.com/otel-demo:adservice|g' kubernetes/opentelemetry-demo.yaml
        sed -i 's|ghcr.io/open-telemetry/demo:.*-productcatalogservice|283565981308.dkr.ecr.us-east-1.amazonaws.com/otel-demo:productcatalogservice|g' kubernetes/opentelemetry-demo.yaml
        sed -i 's|ghcr.io/open-telemetry/demo:.*-quoteservice|283565981308.dkr.ecr.us-east-1.amazonaws.com/otel-demo:quoteservice|g' kubernetes/opentelemetry-demo.yaml
        sed -i 's|ghcr.io/open-telemetry/demo:.*-flagdui|283565981308.dkr.ecr.us-east-1.amazonaws.com/otel-demo:flagdui|g' kubernetes/opentelemetry-demo.yaml
        sed -i 's|ghcr.io/open-telemetry/demo:.*-cartservice|283565981308.dkr.ecr.us-east-1.amazonaws.com/otel-demo:cartservice|g' kubernetes/opentelemetry-demo.yaml
        sed -i 's|ghcr.io/open-telemetry/demo:.*-accountingservice|283565981308.dkr.ecr.us-east-1.amazonaws.com/otel-demo:accountingservice|g' kubernetes/opentelemetry-demo.yaml
        sed -i 's|ghcr.io/open-telemetry/demo:.*-emailservice|283565981308.dkr.ecr.us-east-1.amazonaws.com/otel-demo:emailservice|g' kubernetes/opentelemetry-demo.yaml
        sed -i 's|ghcr.io/open-telemetry/demo:.*-paymentservice|283565981308.dkr.ecr.us-east-1.amazonaws.com/otel-demo:paymentservice|g' kubernetes/opentelemetry-demo.yaml
        sed -i 's|ghcr.io/open-telemetry/demo:.*-imageprovider|283565981308.dkr.ecr.us-east-1.amazonaws.com/otel-demo:imageprovider|g' kubernetes/opentelemetry-demo.yaml
        sed -i 's|ghcr.io/open-telemetry/demo:.*-kafka|283565981308.dkr.ecr.us-east-1.amazonaws.com/otel-demo:kafka|g' kubernetes/opentelemetry-demo.yaml
      run: |
        kubectl rollout status deployment/frontendproxy -n otel-demo
        kubectl rollout status deployment/loadgenerator -n otel-demo
        kubectl rollout status deployment/frontend -n otel-demo
        kubectl rollout status deployment/checkoutservice -n otel-demo
        kubectl rollout status deployment/currencyservice -n otel-demo
        kubectl rollout status deployment/shippingservice -n otel-demo
        kubectl rollout status deployment/frauddetectionservice -n otel-demo
        kubectl rollout status deployment/recommendationservice -n otel-demo
        kubectl rollout status deployment/adservice -n otel-demo
        kubectl rollout status deployment/productcatalogservice -n otel-demo
        kubectl rollout status deployment/quoteservice -n otel-demo
        kubectl rollout status deployment/flagdui -n otel-demo
        kubectl rollout status deployment/cartservice -n otel-demo
        kubectl rollout status deployment/accountingservice -n otel-demo
        kubectl rollout status deployment/emailservice -n otel-demo
        kubectl rollout status deployment/paymentservice -n otel-demo
        kubectl rollout status deployment/imageprovider -n otel-demo
        kubectl rollout status deployment/kafka -n otel-demo
