name: CI/CD Pipeline for AWS EKS

on:
  push:
    branches:
      - main

env:
  ECR_URI: 283565981308.dkr.ecr.us-east-1.amazonaws.com/otel-demo
  AWS_REGION: us-east-1
  EKS_NAMESPACE: otel-demo
  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step to check out the code from the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step to configure AWS credentials using secrets
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    # Step to log in to Amazon ECR
    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    # Update Kubernetes manifests to point to the correct container image
    - name: Update Kubernetes Manifests
      env:
        ECR_URI: ${{ env.ECR_URI }}
      run: |
        sed -i 's|ghcr.io/open-telemetry/demo|$ECR_URI|g' opentelemtry-demo.yaml

    # Update kubeconfig to interact with the correct EKS cluster
    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ env.AWS_REGION }}
        export KUBECONFIG=~/.kube/config

    # Verify the connection to the EKS cluster
    - name: Verify Cluster Connection
      run: |
        echo "Current context:" $(kubectl config current-context)
        kubectl get nodes

    # Ensure the namespace for the deployment exists
    - name: Ensure Namespace Exists
      run: |
        kubectl get namespace ${{ env.EKS_NAMESPACE }} || kubectl create namespace ${{ env.EKS_NAMESPACE }}

    # Apply Kubernetes manifests to deploy to the cluster
    - name: Deploy to Kubernetes
      env:
        EKS_NAMESPACE: ${{ env.EKS_NAMESPACE }}
      run: |
        kubectl apply -f opentelemtry-demo.yaml -n $EKS_NAMESPACE --validate=false

    # Verify the rollout of deployments and collect debug information on failure
    - name: Verify Deployment Rollout
      env:
        EKS_NAMESPACE: ${{ env.EKS_NAMESPACE }}
      run: |
        SERVICES=(
          "opentelemetry-demo-frontendroxy"
          "opentelemetry-demo-loadgenerator"
          "opentelemetry-demo-frontend"
          "opentelemetry-demo-checkoutservice"
          "opentelemetry-demo-currencyservice"
          "opentelemetry-demo-shippingservice"
          "opentelemetry-demo-frauddetectionservice"
          "opentelemetry-demo-recommendationservice"
          "opentelemetry-demo-adservice"
          "opentelemetry-demo-productcatalogservice"
          "opentelemetry-demo-quoteservice"
          "opentelemetry-demo-flagd"
          "opentelemetry-demo-cartservice"
          "opentelemetry-demo-accountingservice"
          "opentelemetry-demo-emailservice"
          "opentelemetry-demo-paymentservice"
          "opentelemetry-demo-imageprovider"
          "opentelemetry-demo-kafka"
        )



  rollback:
    runs-on: ubuntu-latest
    if: failure()
    needs: deploy
    steps:
      - name: Set up AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region us-east-1
  
      - name: Set up kubectl
        run: |
          aws eks --region us-east-1 update-kubeconfig --name otel-demo-cluster
  
      - name: Rollback to previous stable version
        run: |
          kubectl rollout undo deployment/otel-demo-app
