name: CI/CD Pipeline for AWS EKS

on:
  push:
    branches:
      - main

env:
  ECR_URI: 283565981308.dkr.ecr.us-east-1.amazonaws.com/otel-demo
  AWS_REGION: us-east-1
  EKS_NAMESPACE: otel-demo

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Update Kubernetes Manifests
      env:
        ECR_URI: ${{ env.ECR_URI }}
      run: |
        sed -i 's|ghcr.io/open-telemetry/demo|$ECR_URI|g' opentelemtry-demo.yaml

    - name: Ensure Namespace Exists
      run: |
        kubectl get namespace ${{ env.EKS_NAMESPACE }} || kubectl create namespace ${{ env.EKS_NAMESPACE }}

    - name: Update kubeconfig
      run: aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ env.AWS_REGION }}

    - name: Deploy to Kubernetes
      env:
        EKS_NAMESPACE: ${{ env.EKS_NAMESPACE }}
      run: |
        kubectl apply -f opentelemtry-demo.yaml -n $EKS_NAMESPACE --validate=false

    - name: Verify Deployment Rollout
      env:
        EKS_NAMESPACE: ${{ env.EKS_NAMESPACE }}
      run: |
        SERVICES=(
          "frontendproxy"
          "loadgenerator"
          "frontend"
          "checkoutservice"
          "currencyservice"
          "shippingservice"
          "frauddetectionservice"
          "recommendationservice"
          "adservice"
          "productcatalogservice"
          "quoteservice"
          "flagdui"
          "cartservice"
          "accountingservice"
          "emailservice"
          "paymentservice"
          "imageprovider"
          "kafka"
        )
        for SERVICE in "${SERVICES[@]}"; do
          kubectl rollout status deployment/$SERVICE -n $EKS_NAMESPACE
        done
